#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

#compositer 
picom -b &

#satusbar
slstatus &

# Wallpaper 
nitrogen --restore &

exec dwm
